### ISSUE TITLE
Policy with ${aws:username} is not evaluating properly. Policy with 'red' does.

### ISSUE THREAD

**Issue by dkilcy** [scality/Arsenal#144]
GA6.2.0-beta5-rc3
CentOS 7.2

My use-case is to simulate a 'home' directory where user 'red' cannot see contents of user 'black' folder like a Linux filesystem.

I created a bucket 'mybucket' with:
- mybucket/home/red/file1
- mybucket/home/red/file2
- mybucket/home/black/file1
- mybucket/home/black/file2

and hoped that the below policy would prevent 'red' from seeing files under mybucket/home/black and vice-versa, but get AccessDenied trying to list anything under the bucket as either 'red' or 'black' user.

If I replace occurrances of `${aws:username}` to `red` in the below policy and attach it to the 'red' user, I get the expected results - that user `red` can only see `mybucket/home/red/fileX ` and gets access denied on `mybucket/home/black/fileX`

```
{
  "Version": "2012-10-17",
  "Statement": [
    {"Sid": "AllowGroupToSeeBucketList",
     "Action": ["s3:ListAllMyBuckets", "s3:GetBucketLocation"],
     "Effect": "Allow",
     "Resource": ["arn:aws:s3:::*"]},
    {"Sid": "AllowRootLevelListingOfThisBucketAndHomePrefix",
     "Action": ["s3:ListBucket"],
     "Effect": "Allow",
     "Resource": ["arn:aws:s3:::mybucket"],
     "Condition": {"StringEquals":{"s3:prefix": ["","home/"],"s3:delimiter":["/"]}}},
    {"Sid": "AllowListBucketofASepecificUserPrefix",
      "Action": ["s3:ListBucket"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::mybucket"],
      "Condition": {"StringLike": {"s3:prefix":["home/${aws:username}/*"]}}},
    {"Sid": "AllowUserFullAcccesstoJustSpecificUserPrefix",
      "Action": ["s3:*"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::mybucket/home/${aws:username}",
                   "arn:aws:s3:::mybucket/home/${aws:username}/*"]}
  ]
}
```

See: https://github.com/scality/IronMan-TS/blob/master/IAM-Vault.md#giving-a-user-a-home-directory

**Comment by LaurenSpiegel** [comment]
I just tested this and it works as expected for me.

**Red getting access denied to list black's objects:**

``
lhs:~/ $ aws s3api list-objects --bucket mybucket --prefix home/black/  --endpoint-url http://localhost:8000

A client error (AccessDenied) occurred when calling the ListObjects operation: Access Denied
``


**Red getting access to list red's objects (make sure you have "/" after "red" in the prefix):**

``
lhs:~/ $ aws s3api list-objects --bucket mybucket --prefix home/red/  --endpoint-url http://localhost:8000
None
CONTENTS	"d41d8cd98f00b204e9800998ecf8427e"	home/red/file1	2016-08-29T17:18:26.539Z	0	STANDARD
OWNER	test	F962T22H86EDEMBV97U5OYUMTP4E9DERWNGH1XZVVLUKNIMNO4NGPMNQ3O9YMTJF
CONTENTS	"d41d8cd98f00b204e9800998ecf8427e"	home/red/file2	2016-08-29T17:18:29.350Z	0	STANDARD
OWNER	test	F962T22H86EDEMBV97U5OYUMTP4E9DERWNGH1XZVVLUKNIMNO4NGPMNQ3O9YMTJF
``


Also, note for seeing that red has permission on listing the whole bucket or anything with the home/ prefix, you must include a delimiter of "/" in the listing request (red only gets to see the rolled up results).  I tested and our behavior is the same as AWS.

**Red gets access denied for general listing without delimiter:**
``
lhs:~/ $ aws s3api list-objects --bucket mybucket --prefix home/  --endpoint-url http://localhost:8000

A client error (AccessDenied) occurred when calling the ListObjects operation: Access Denied
``

**Red gets access for general listing with delimiter:**

``
lhs:~/ $ aws s3api list-objects --bucket mybucket --prefix "" --delimiter / --endpoint-url http://localhost:8000
COMMONPREFIXES	home/
CONTENTS	"d41d8cd98f00b204e9800998ecf8427e"	home	2016-08-29T17:18:12.507Z	0	STANDARD
OWNER	test	F962T22H86EDEMBV97U5OYUMTP4E9DERWNGH1XZVVLUKNIMNO4NGPMNQ3O9YMTJF
lhs:~/ $ aws s3api list-objects --bucket mybucket --prefix home/ --delimiter / --endpoint-url http://localhost:8000
COMMONPREFIXES	home/black/
COMMONPREFIXES	home/red/
CONTENTS	"d41d8cd98f00b204e9800998ecf8427e"	home/black	2016-08-29T17:18:35.477Z	0	STANDARD
OWNER	test	F962T22H86EDEMBV97U5OYUMTP4E9DERWNGH1XZVVLUKNIMNO4NGPMNQ3O9YMTJF
CONTENTS	"d41d8cd98f00b204e9800998ecf8427e"	home/red	2016-08-29T17:18:21.223Z	0	STANDARD
OWNER	test	F962T22H86EDEMBV97U5OYUMTP4E9DERWNGH1XZVVLUKNIMNO4NGPMNQ3O9YMTJF
``

**Comment by LaurenSpiegel** [comment]
Here are the expected results for black as well:

**Access denied to list red's objects:**

```
lhs:~/ $ aws s3api list-objects --bucket mybucket --prefix home/red/  --endpoint-url http://localhost:8000

A client error (AccessDenied) occurred when calling the ListObjects operation: Access Denied
lhs:~/ $ aws s3api list-objects --bucket mybucket --prefix home/red  --endpoint-url http://localhost:8000

A client error (AccessDenied) occurred when calling the ListObjects operation: Access Denied
```

**Access granted to list black's objects:**

```
lhs:~/ $ aws s3api list-objects --bucket mybucket --prefix home/black/  --endpoint-url http://localhost:8000
None
CONTENTS	"d41d8cd98f00b204e9800998ecf8427e"	home/black/file1	2016-08-29T17:18:41.011Z	0	STANDARD
OWNER	test	F962T22H86EDEMBV97U5OYUMTP4E9DERWNGH1XZVVLUKNIMNO4NGPMNQ3O9YMTJF
CONTENTS	"d41d8cd98f00b204e9800998ecf8427e"	home/black/file2	2016-08-29T17:18:43.423Z	0	STANDARD
OWNER	test	F962T22H86EDEMBV97U5OYUMTP4E9DERWNGH1XZVVLUKNIMNO4NGPMNQ3O9YMTJF
```

**Comment by dkilcy** [comment]
I still owe you guys the results of my test.

**Comment by rahulreddy** [comment]
@dkilcy I am closing the issue for now. Please feel free to re-open if you are able to reproduce the bug.
