### ISSUE TITLE
rel6/2 does not have the listing fix

### ISSUE THREAD

**Issue by vrancurel** [scality/Arsenal#160]
was merged apparently only on rel/1.1
https://github.com/scality/Arsenal/pull/152

**Comment by DavidPineauScality** [comment]
Then we only need to forward port it, and we'll have the fix for the new RC/The actual GA ?

**Comment by alexandre-merle** [comment]
was merged against master too https://github.com/scality/Arsenal/pull/148

**Comment by vrancurel** [comment]
@RachedBenMustapha please be aware when we'll build the GA

**Comment by RachedBenMustapha** [comment]
The `rel/6.2` branch was recreated from `master`, so the fix is now included.
