### ISSUE TITLE
Auth v4 canonical request

### ISSUE THREAD

**Issue by alexandre-merle** [scality/Arsenal#175]
The computation of the canonical request should normalize the request path, like this

```
GET /example/.. HTTP/1.1
Host:example.amazonaws.com
X-Amz-Date:20150830T123600Z
```

should result in :

```
GET
/

host:example.amazonaws.com
x-amz-date:20150830T123600Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

This fix need to be done against rel/6.2

Note: This behavior is not use for s3 requests, but every other services

**Comment by LaurenSpiegel** [comment]
Very important  -- any normalizing should NOT be used for requests to S3.

In exception to this, you do not normalize URI paths for requests to Amazon S3. For example, if you have a bucket with an object named my-object//example//photo.user, use that path. Normalizing the path to my-object/example/photo.user will cause the request to fail.
