### ISSUE TITLE
COMPAT: return AccessDenied if Date before epochTime (01/01/1970)

### ISSUE THREAD

**Issue by nicolas2bert** [scality/Arsenal#198]
On **ceph/s3-tests**, these changes fix:

`FAIL: s3tests.functional.test_headers.test_object_create_bad_date_before_epoch_aws2`
`FAIL: s3tests.functional.test_headers.test_bucket_create_bad_date_before_epoch_aws2`

**Comment by DavidPineauScality** [comment]
Does this mean a negative timestamp ? :D (just.. wat :D)

**Comment by nicolas2bert** [comment]
Yes ! :)

**Comment by nicolas2bert** [comment]
Should I instead of declaring `const epochTime = new Date('1970-01-01').getTime();`
checking for `timestamp < 0` ? 
I thought declaring `const epochTime = new Date('1970-01-01').getTime();` made it clearer.

**Comment by DavidPineauScality** [comment]
Well, I think it's fine this way. Just wanted to confirm my understanding of the issue.
