### ISSUE TITLE
Logs are broken

### ISSUE THREAD

**Issue by rom-stratoscale** [scality/Arsenal#319]
Running scality S3 (39cf1fae5cdfd320510abffad76f7de280b7ce11) over arsenal master....
 
s3-scality.service.strato | > s3@7.0.0 start_dataserver /usr/src/app
s3-scality.service.strato | > node dataserver.js
s3-scality.service.strato | 
s3-scality.service.strato | /usr/src/app/node_modules/arsenal/lib/auth/in_memory/validateAuthConfig.js:177
s3-scality.service.strato |     const log = new (logApi || werelogs).Logger('S3');
s3-scality.service.strato |                 ^
s3-scality.service.strato | 
s3-scality.service.strato | TypeError: (logApi || werelogs).Logger is not a constructor
s3-scality.service.strato |     at validateAuthConfig (/usr/src/app/node_modules/arsenal/lib/auth/in_memory/validateAuthConfig.js:177:17)
s3-scality.service.strato |     at Config._configureBackends (/usr/src/app/lib/Config.js:620:17)
s3-scality.service.strato |     at new Config (/usr/src/app/lib/Config.js:121:14)
s3-scality.service.strato |     at Object.<anonymous> (/usr/src/app/lib/Config.js:660:13)
s3-scality.service.strato |     at Module._compile (module.js:570:32)
s3-scality.service.strato |     at Object.Module._extensions..js (module.js:579:10)
s3-scality.service.strato |     at Module.load (module.js:487:32)
s3-scality.service.strato |     at tryModuleLoad (module.js:446:12)
s3-scality.service.strato |     at Function.Module._load (module.js:438:3)
s3-scality.service.strato |     at Module.require (module.js:497:17)

I think it broke something

**Comment by DavidPineauScality** [comment]
This means that the tests did not catch a call to the `validateAuthConfig` function. Fixing the way it's called should be enough.

**Comment by rom-stratoscale** [comment]
can you elaborate please? I actually did nothing on S3 side. Just rebuild the docker image.

**Comment by DavidPineauScality** [comment]
As you can see in https://github.com/scality/Arsenal/pull/314/files#diff-3730f90bb19d3b3646a968c2a4dddbdeL169 ;  a project-wide change was made to werelogs to fix an insidious configuration bug; and led to a change in the API of a few common/library functions.

I may have missed some calls to this library in various projects, due to lack of automated testing and attention. If you find any, you may fix it following the method used in the same PR: https://github.com/scality/Arsenal/pull/314/files#diff-a400b2bf757d4e597747b3bd4a2105ddR33

**Comment by DavidPineauScality** [comment]
Alternatively, you may want to make sure you installed the proper versions of arsenal and werelogs, by removing your node_modules, and re-installing the dependencies (since we know npm doesn't handle git branches very well)

**Comment by DavidPineauScality** [comment]
After testing it out, I see it working (of course, you may need to rm -rf node_modules; then npm install ; before this works, as I described earlier).
That being said, I found out an obsolete piece of code in the S3 repository at https://github.com/scality/S3/blob/master/dataserver.js#L15 (The config bit about the logs in this line is not taken into account by Arsenal, so it might as well be removed). I'll leave the S3 team to handle this.

Then, Can we close this issue ?

**Comment by rom-stratoscale** [comment]
Sure. Closing.
